Added exception for workspaces not found
Error retrieving workspace information for workspace encode-tutorial/ENCODE-Tutorial-May-2020
{
  "causes": [],
  "message": "workspace encode-tutorial/ENCODE-Tutorial-May-2020 does not exist or you do not have permission to use it",
  "source": "rawls",
  "stackTrace": [],
  "statusCode": 404,
  "timestamp": 1740789100712
}
Traceback (most recent call last):
  File "/home/runner/work/terra-featured-workspace-***s/terra-featured-workspace-***s/featured_workspaces_***.py", line 371, in <module>
    ***_all(args)
  File "/home/runner/work/terra-featured-workspace-***s/terra-featured-workspace-***s/featured_workspaces_***.py", line 194, in ***_all
    fws = format_fws(verbose=False)
  File "/home/runner/work/terra-featured-workspace-***s/terra-featured-workspace-***s/get_fws.py", line 91, in format_fws
    cloudplatform = get_cloudPlatform(ws_project, ws_name)
  File "/home/runner/work/terra-featured-workspace-***s/terra-featured-workspace-***s/get_fws.py", line 76, in get_cloudPlatform
    return fws_cloudplatform['workspace']['cloudPlatform']
KeyError: 'workspace'